from __future__ import annotations

from typing import Dict, List

from .models import (
    AnatomicalZone,
    COLONOSCOPY_ZONES,
    GASTROSCOPY_ZONES,
    ObservationType,
)


ZONE_LABELS: Dict[AnatomicalZone, str] = {
    AnatomicalZone.ESOPHAGUS: "Пищевод",
    AnatomicalZone.UPPER_ESOPHAGUS: "Верхняя треть пищевода",
    AnatomicalZone.MIDDLE_ESOPHAGUS: "Средняя треть пищевода",
    AnatomicalZone.LOWER_ESOPHAGUS: "Нижняя треть пищевода",
    AnatomicalZone.Z_LINE: "Z-линия",
    AnatomicalZone.GE_JUNCTION: "Пищеводно-желудочный переход",
    AnatomicalZone.CARDIA: "Кардия",
    AnatomicalZone.FUNDUS: "Дно желудка",
    AnatomicalZone.GASTRIC_BODY: "Тело желудка",
    AnatomicalZone.UPPER_STOMACH: "Верхняя треть желудка",
    AnatomicalZone.MIDDLE_STOMACH: "Средняя треть желудка",
    AnatomicalZone.LOWER_STOMACH: "Нижняя треть желудка",
    AnatomicalZone.LESSER_CURVATURE: "Малая кривизна желудка",
    AnatomicalZone.GREATER_CURVATURE: "Большая кривизна желудка",
    AnatomicalZone.INCISURA: "Угол желудка",
    AnatomicalZone.ANTRUM: "Антральный отдел",
    AnatomicalZone.PYLORUS: "Привратник",
    AnatomicalZone.DUODENAL_BULB: "Луковица ДПК",
    AnatomicalZone.DUODENUM_D2: "Постбульбарный отдел ДПК",
    AnatomicalZone.DUODENUM_UNSPECIFIED: "Двенадцатиперстная кишка",
    AnatomicalZone.STOMACH_UNSPECIFIED: "Желудок неуточнённо",
    AnatomicalZone.UPPER_GI_UNSPECIFIED: "Верхние отделы ЖКТ неуточнённо",
    AnatomicalZone.PERIANAL: "Перианальная область",
    AnatomicalZone.ANAL_CANAL: "Анальный канал",
    AnatomicalZone.RECTUM: "Прямая кишка",
    AnatomicalZone.RECTOSIGMOID: "Ректосигмоидный отдел",
    AnatomicalZone.SIGMOID_COLON: "Сигмовидная кишка",
    AnatomicalZone.DESCENDING_COLON: "Нисходящая ободочная кишка",
    AnatomicalZone.SPLENIC_FLEXURE: "Селезёночный изгиб",
    AnatomicalZone.TRANSVERSE_COLON: "Поперечная ободочная кишка",
    AnatomicalZone.HEPATIC_FLEXURE: "Печёночный изгиб",
    AnatomicalZone.ASCENDING_COLON: "Восходящая ободочная кишка",
    AnatomicalZone.CECUM: "Слепая кишка",
    AnatomicalZone.CECAL_POLE: "Купол слепой кишки",
    AnatomicalZone.APPENDICEAL_ORIFICE: "Устье аппендикса",
    AnatomicalZone.ILEOCECAL_VALVE: "Илеоцекальный клапан",
    AnatomicalZone.TERMINAL_ILEUM: "Терминальный отдел подвздошной кишки",
    AnatomicalZone.COLON_UNSPECIFIED: "Ободочная кишка неуточнённо",
    AnatomicalZone.LARGE_BOWEL_UNSPECIFIED: "Толстая кишка неуточнённо",
    AnatomicalZone.LEFT_COLON: "Левые отделы толстой кишки",
    AnatomicalZone.RIGHT_COLON: "Правые отделы толстой кишки",
    AnatomicalZone.UNKNOWN: "Зона не уточнена",
}


OBSERVATION_LABELS: Dict[ObservationType, str] = {
    ObservationType.NORMAL: "норма",
    ObservationType.POLYP: "полип",
    ObservationType.MASS: "образование",
    ObservationType.TUMOR: "опухоль",
    ObservationType.SUBMUCOSAL_LESION: "подслизистое образование",
    ObservationType.EROSION: "эрозия",
    ObservationType.ULCER: "язва",
    ObservationType.APHTHA: "афта",
    ObservationType.ERYTHEMA: "гиперемия",
    ObservationType.INFLAMMATION: "воспаление",
    ObservationType.EDEMA: "отёк",
    ObservationType.GRANULARITY: "зернистость слизистой",
    ObservationType.FRIABILITY: "рыхлость слизистой",
    ObservationType.CONTACT_BLEEDING: "контактная кровоточивость",
    ObservationType.BLEEDING: "кровотечение",
    ObservationType.BLOOD_IN_LUMEN: "следы крови",
    ObservationType.HEMORRHAGE: "геморрагии",
    ObservationType.VASCULAR_ECTASIA: "сосудистая мальформация",
    ObservationType.DIVERTICULUM: "дивертикул",
    ObservationType.STENOSIS: "стеноз",
    ObservationType.DEFORMITY: "деформация",
    ObservationType.SCAR: "рубец",
    ObservationType.ATROPHY: "атрофия",
    ObservationType.METAPLASIA: "метаплазия",
    ObservationType.SUSPECTED_DYSPLASIA: "дисплазия подозрение",
    ObservationType.SUSPECTED_BARRETT: "пищевод Барретта подозрение",
    ObservationType.ESOPHAGITIS: "эзофагит",
    ObservationType.HIATAL_HERNIA: "грыжа пищеводного отверстия",
    ObservationType.VARICES: "варикозные вены",
    ObservationType.CANDIDIASIS: "кандидоз",
    ObservationType.GASTRITIS: "гастрит",
    ObservationType.GASTROPATHY: "гастропатия",
    ObservationType.DUODENITIS: "дуоденит",
    ObservationType.BULBITIS: "бульбит",
    ObservationType.BILE_REFLUX: "желчь в желудке",
    ObservationType.RETAINED_CONTENT: "застой содержимого",
    ObservationType.FOREIGN_BODY: "инородное тело",
    ObservationType.COLITIS: "колит",
    ObservationType.PROCTITIS: "проктит",
    ObservationType.ILEITIS: "илеит",
    ObservationType.PSEUDOMEMBRANES: "псевдомембраны",
    ObservationType.MELANOSIS_COLI: "меланоз",
    ObservationType.HEMORRHOIDS: "геморрой",
    ObservationType.ANAL_FISSURE: "анальная трещина",
    ObservationType.FISTULA: "свищ",
    ObservationType.POOR_PREP: "подготовка недостаточная",
    ObservationType.STOOL_RESIDUE: "остаточное содержимое",
    ObservationType.BIOPSY_TAKEN: "биопсия взята",
    ObservationType.RESECTION_PERFORMED: "удаление образования",
    ObservationType.OTHER: "другое",
}


ZONE_SYNONYMS: Dict[AnatomicalZone, List[str]] = {
    AnatomicalZone.ESOPHAGUS: ["пищевод", "в пищеводе", "esophagus", "oesophagus", "эзофагус"],
    AnatomicalZone.UPPER_ESOPHAGUS: ["верхняя треть пищевода", "проксимальный пищевод", "верхний отдел пищевода", "upper esophagus", "proximal esophagus"],
    AnatomicalZone.MIDDLE_ESOPHAGUS: ["средняя треть пищевода", "средний отдел пищевода", "middle esophagus", "mid esophagus"],
    AnatomicalZone.LOWER_ESOPHAGUS: ["нижняя треть пищевода", "дистальный пищевод", "нижний отдел пищевода", "distal esophagus", "lower esophagus"],
    AnatomicalZone.Z_LINE: ["z-линия", "зубчатая линия", "линия z", "squamocolumnar junction", "SCJ"],
    AnatomicalZone.GE_JUNCTION: ["пищеводно-желудочный переход", "эзофагогастральный переход", "гастроэзофагеальный переход", "кардия на уровне перехода", "GEJ", "gastroesophageal junction"],
    AnatomicalZone.CARDIA: ["кардия", "кардиальный отдел", "cardia", "gastric cardia"],
    AnatomicalZone.FUNDUS: ["дно желудка", "фундальный отдел", "fundus", "gastric fundus"],
    AnatomicalZone.GASTRIC_BODY: ["тело желудка", "в теле желудка", "corpus", "gastric body", "body of stomach"],
    AnatomicalZone.UPPER_STOMACH: ["верхняя треть желудка", "проксимальный отдел желудка", "proximal stomach"],
    AnatomicalZone.MIDDLE_STOMACH: ["средняя треть желудка", "средний отдел желудка", "mid stomach"],
    AnatomicalZone.LOWER_STOMACH: ["нижняя треть желудка", "дистальный отдел желудка", "distal stomach"],
    AnatomicalZone.LESSER_CURVATURE: ["малая кривизна", "по малой кривизне", "lesser curvature"],
    AnatomicalZone.GREATER_CURVATURE: ["большая кривизна", "по большой кривизне", "greater curvature"],
    AnatomicalZone.INCISURA: ["угол желудка", "incisura", "angulus", "incisura angularis"],
    AnatomicalZone.ANTRUM: ["антрум", "антральный отдел", "препилорический отдел", "antrum", "gastric antrum", "prepyloric region"],
    AnatomicalZone.PYLORUS: ["привратник", "пилорус", "область привратника", "pylorus", "pyloric channel"],
    AnatomicalZone.DUODENAL_BULB: ["луковица двенадцатиперстной кишки", "луковица ДПК", "bulb", "duodenal bulb", "D1"],
    AnatomicalZone.DUODENUM_D2: ["постбульбарный отдел", "нисходящий отдел ДПК", "вторая часть ДПК", "D2", "second part of duodenum"],
    AnatomicalZone.DUODENUM_UNSPECIFIED: ["двенадцатиперстная кишка", "ДПК", "duodenum"],
    AnatomicalZone.STOMACH_UNSPECIFIED: ["желудок", "в желудке", "слизистая желудка", "gastric", "stomach"],
    AnatomicalZone.UPPER_GI_UNSPECIFIED: ["верхние отделы ЖКТ", "upper GI", "upper gastrointestinal tract"],
    AnatomicalZone.PERIANAL: ["перианальная область", "перианально", "perianal area", "perianal region"],
    AnatomicalZone.ANAL_CANAL: ["анальный канал", "анус", "задний проход", "anal canal", "anus"],
    AnatomicalZone.RECTUM: ["прямая кишка", "в прямой кишке", "ректум", "rectum", "rectal"],
    AnatomicalZone.RECTOSIGMOID: ["ректосигмоидный отдел", "ректосигма", "rectosigmoid", "rectosigmoid junction"],
    AnatomicalZone.SIGMOID_COLON: ["сигмовидная кишка", "сигма", "в сигме", "sigmoid colon", "sigmoid"],
    AnatomicalZone.DESCENDING_COLON: ["нисходящая ободочная кишка", "нисходящая кишка", "descending colon"],
    AnatomicalZone.SPLENIC_FLEXURE: ["селезёночный изгиб", "левый изгиб ободочной кишки", "splenic flexure", "left colic flexure"],
    AnatomicalZone.TRANSVERSE_COLON: ["поперечная ободочная кишка", "поперечная кишка", "transverse colon"],
    AnatomicalZone.HEPATIC_FLEXURE: ["печёночный изгиб", "правый изгиб ободочной кишки", "hepatic flexure", "right colic flexure"],
    AnatomicalZone.ASCENDING_COLON: ["восходящая ободочная кишка", "восходящая кишка", "ascending colon"],
    AnatomicalZone.CECUM: ["слепая кишка", "цекум", "caecum", "cecum"],
    AnatomicalZone.CECAL_POLE: ["купол слепой кишки", "дно слепой кишки", "cecal pole", "cecal base"],
    AnatomicalZone.APPENDICEAL_ORIFICE: ["устье аппендикса", "аппендикулярное отверстие", "appendiceal orifice"],
    AnatomicalZone.ILEOCECAL_VALVE: ["илеоцекальный клапан", "баугиниева заслонка", "илеоцекальная заслонка", "ileocecal valve", "IC valve"],
    AnatomicalZone.TERMINAL_ILEUM: ["терминальный отдел подвздошной кишки", "терминальный илеум", "terminal ileum", "TI"],
    AnatomicalZone.COLON_UNSPECIFIED: ["ободочная кишка", "colon", "colonic"],
    AnatomicalZone.LARGE_BOWEL_UNSPECIFIED: ["толстая кишка", "large bowel", "large intestine"],
    AnatomicalZone.LEFT_COLON: ["левые отделы толстой кишки", "left colon", "left-sided colon"],
    AnatomicalZone.RIGHT_COLON: ["правые отделы толстой кишки", "right colon", "right-sided colon"],
}


OBSERVATION_SYNONYMS: Dict[ObservationType, List[str]] = {
    ObservationType.NORMAL: ["норма", "без патологии", "патологических изменений не выявлено", "слизистая без особенностей", "normal", "unremarkable"],
    ObservationType.POLYP: ["полип", "полиповидное образование", "polyp", "polypoid lesion", "polypoid formation"],
    ObservationType.MASS: ["образование", "опухолевидное образование", "объемное образование", "mass", "lesion", "tumor-like lesion"],
    ObservationType.TUMOR: ["опухоль", "новообразование", "tumor", "neoplasm", "malignant-looking lesion", "suspicious mass"],
    ObservationType.SUBMUCOSAL_LESION: ["подслизистое образование", "субмукозное образование", "submucosal lesion", "subepithelial lesion"],
    ObservationType.EROSION: ["эрозия", "эрозивный дефект", "поверхностный дефект слизистой", "erosion", "erosive defect"],
    ObservationType.ULCER: ["язва", "язвенный дефект", "ulcer", "ulcerative defect"],
    ObservationType.APHTHA: ["афта", "афтозное поражение", "aphtha", "aphthous lesion"],
    ObservationType.ERYTHEMA: ["гиперемия", "покраснение", "эритема", "erythema", "hyperemia", "redness"],
    ObservationType.INFLAMMATION: ["воспаление", "воспалительные изменения", "inflammatory changes", "inflammation"],
    ObservationType.EDEMA: ["отек", "отёк слизистой", "отечность", "edema", "mucosal edema"],
    ObservationType.GRANULARITY: ["зернистость", "granular mucosa", "mucosal granularity"],
    ObservationType.FRIABILITY: ["рыхлая слизистая", "friable mucosa", "friability"],
    ObservationType.CONTACT_BLEEDING: ["контактная кровоточивость", "кровоточит при контакте", "contact bleeding", "touch bleeding"],
    ObservationType.BLEEDING: ["кровотечение", "активное кровотечение", "bleeding", "active bleeding", "hemorrhage"],
    ObservationType.BLOOD_IN_LUMEN: ["следы крови", "кровь в просвете", "old blood", "fresh blood", "blood in lumen"],
    ObservationType.HEMORRHAGE: ["геморрагии", "петехии", "точечные кровоизлияния", "hemorrhagic spots", "petechiae"],
    ObservationType.VASCULAR_ECTASIA: ["сосудистая мальформация", "ангиодисплазия", "angiodysplasia", "vascular ectasia", "AVM"],
    ObservationType.DIVERTICULUM: ["дивертикул", "дивертикулы", "дивертикулез", "diverticulum", "diverticula", "diverticulosis"],
    ObservationType.STENOSIS: ["стеноз", "сужение просвета", "стриктура", "narrowing", "stenosis", "stricture"],
    ObservationType.DEFORMITY: ["деформация", "деформация просвета", "деформация складок", "deformity"],
    ObservationType.SCAR: ["рубец", "рубцовые изменения", "scar", "scarring", "post-ulcer scar"],
    ObservationType.ATROPHY: ["атрофия", "атрофичная слизистая", "атрофические изменения", "atrophy", "atrophic mucosa"],
    ObservationType.METAPLASIA: ["метаплазия", "кишечная метаплазия", "intestinal metaplasia", "metaplastic changes"],
    ObservationType.SUSPECTED_DYSPLASIA: ["подозрение на дисплазию", "диспластические изменения", "suspected dysplasia", "dysplastic changes"],
    ObservationType.SUSPECTED_BARRETT: ["пищевод Барретта", "подозрение на Барретта", "Barrett", "Barrett's esophagus", "suspected Barrett"],
    ObservationType.ESOPHAGITIS: ["эзофагит", "рефлюкс-эзофагит", "reflux esophagitis", "esophagitis"],
    ObservationType.HIATAL_HERNIA: ["грыжа пищеводного отверстия диафрагмы", "ГПОД", "хиатальная грыжа", "hiatal hernia", "hiatus hernia"],
    ObservationType.VARICES: ["варикозные вены", "вариксы", "esophageal varices", "gastric varices", "varices"],
    ObservationType.CANDIDIASIS: ["кандидоз", "кандидозный эзофагит", "Candida", "candidiasis"],
    ObservationType.GASTRITIS: ["гастрит", "воспаление желудка", "gastritis"],
    ObservationType.GASTROPATHY: ["гастропатия", "hyperemic gastropathy", "erosive gastropathy", "hemorrhagic gastropathy", "gastropathy"],
    ObservationType.DUODENITIS: ["дуоденит", "воспаление ДПК", "duodenitis"],
    ObservationType.BULBITIS: ["бульбит", "воспаление луковицы ДПК", "bulbitis"],
    ObservationType.BILE_REFLUX: ["желчь в желудке", "дуоденогастральный рефлюкс", "bile reflux", "bile in stomach"],
    ObservationType.RETAINED_CONTENT: ["застой содержимого", "остатки пищи", "retained food", "gastric retention"],
    ObservationType.FOREIGN_BODY: ["инородное тело", "foreign body"],
    ObservationType.COLITIS: ["колит", "воспаление толстой кишки", "colitis"],
    ObservationType.PROCTITIS: ["проктит", "воспаление прямой кишки", "proctitis"],
    ObservationType.ILEITIS: ["илеит", "воспаление терминального илеума", "ileitis", "terminal ileitis"],
    ObservationType.PSEUDOMEMBRANES: ["псевдомембраны", "псевдомембранозный колит", "pseudomembranes", "pseudomembranous colitis"],
    ObservationType.MELANOSIS_COLI: ["меланоз", "меланоз толстой кишки", "melanosis coli"],
    ObservationType.HEMORRHOIDS: ["геморрой", "геморроидальные узлы", "hemorrhoids", "haemorrhoids"],
    ObservationType.ANAL_FISSURE: ["анальная трещина", "fissure", "anal fissure"],
    ObservationType.FISTULA: ["свищ", "fistula"],
    ObservationType.POOR_PREP: ["плохая подготовка", "недостаточная подготовка", "кишечник подготовлен неудовлетворительно", "poor bowel preparation", "inadequate prep"],
    ObservationType.STOOL_RESIDUE: ["остаточное содержимое", "каловые массы", "stool residue", "fecal residue"],
    ObservationType.BIOPSY_TAKEN: ["биопсия", "взята биопсия", "biopsy taken", "biopsied"],
    ObservationType.RESECTION_PERFORMED: ["удален полип", "полипэктомия", "резекция", "polypectomy", "resection", "EMR"],
}


def export_nomenclature() -> dict:
    return {
        "gastroscopy_zones": _zone_entries(GASTROSCOPY_ZONES),
        "colonoscopy_zones": _zone_entries(COLONOSCOPY_ZONES),
        "finding_types": [
            {
                "code": observation_type.value,
                "label": OBSERVATION_LABELS[observation_type],
                "synonyms": OBSERVATION_SYNONYMS.get(observation_type, []),
            }
            for observation_type in sorted(ObservationType, key=lambda item: item.value)
        ],
    }


def _zone_entries(zones) -> List[dict]:
    return [
        {
            "code": zone.value,
            "label": ZONE_LABELS[zone],
            "synonyms": ZONE_SYNONYMS.get(zone, []),
        }
        for zone in sorted(zones, key=lambda item: item.value)
    ]
